// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package autoswap

import (
	"github.com/lightzapp/lightz-client/internal/database"
	"github.com/lightzapp/lightz-client/internal/lightning"
	"github.com/lightzapp/lightz-client/internal/onchain"
	"github.com/lightzapp/lightz-client/pkg/lightz"
	"github.com/lightzapp/lightz-client/pkg/lightzrpc"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRpcProvider creates a new instance of MockRpcProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRpcProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRpcProvider {
	mock := &MockRpcProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRpcProvider is an autogenerated mock type for the RpcProvider type
type MockRpcProvider struct {
	mock.Mock
}

type MockRpcProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRpcProvider) EXPECT() *MockRpcProvider_Expecter {
	return &MockRpcProvider_Expecter{mock: &_m.Mock}
}

// CreateAutoChainSwap provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) CreateAutoChainSwap(tenant *database.Tenant, request *lightzrpc.CreateChainSwapRequest) error {
	ret := _mock.Called(tenant, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAutoChainSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.Tenant, *lightzrpc.CreateChainSwapRequest) error); ok {
		r0 = returnFunc(tenant, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcProvider_CreateAutoChainSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAutoChainSwap'
type MockRpcProvider_CreateAutoChainSwap_Call struct {
	*mock.Call
}

// CreateAutoChainSwap is a helper method to define mock.On call
//   - tenant *database.Tenant
//   - request *lightzrpc.CreateChainSwapRequest
func (_e *MockRpcProvider_Expecter) CreateAutoChainSwap(tenant interface{}, request interface{}) *MockRpcProvider_CreateAutoChainSwap_Call {
	return &MockRpcProvider_CreateAutoChainSwap_Call{Call: _e.mock.On("CreateAutoChainSwap", tenant, request)}
}

func (_c *MockRpcProvider_CreateAutoChainSwap_Call) Run(run func(tenant *database.Tenant, request *lightzrpc.CreateChainSwapRequest)) *MockRpcProvider_CreateAutoChainSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Tenant
		if args[0] != nil {
			arg0 = args[0].(*database.Tenant)
		}
		var arg1 *lightzrpc.CreateChainSwapRequest
		if args[1] != nil {
			arg1 = args[1].(*lightzrpc.CreateChainSwapRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcProvider_CreateAutoChainSwap_Call) Return(err error) *MockRpcProvider_CreateAutoChainSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcProvider_CreateAutoChainSwap_Call) RunAndReturn(run func(tenant *database.Tenant, request *lightzrpc.CreateChainSwapRequest) error) *MockRpcProvider_CreateAutoChainSwap_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAutoReverseSwap provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) CreateAutoReverseSwap(tenant *database.Tenant, request *lightzrpc.CreateReverseSwapRequest) error {
	ret := _mock.Called(tenant, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAutoReverseSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.Tenant, *lightzrpc.CreateReverseSwapRequest) error); ok {
		r0 = returnFunc(tenant, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcProvider_CreateAutoReverseSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAutoReverseSwap'
type MockRpcProvider_CreateAutoReverseSwap_Call struct {
	*mock.Call
}

// CreateAutoReverseSwap is a helper method to define mock.On call
//   - tenant *database.Tenant
//   - request *lightzrpc.CreateReverseSwapRequest
func (_e *MockRpcProvider_Expecter) CreateAutoReverseSwap(tenant interface{}, request interface{}) *MockRpcProvider_CreateAutoReverseSwap_Call {
	return &MockRpcProvider_CreateAutoReverseSwap_Call{Call: _e.mock.On("CreateAutoReverseSwap", tenant, request)}
}

func (_c *MockRpcProvider_CreateAutoReverseSwap_Call) Run(run func(tenant *database.Tenant, request *lightzrpc.CreateReverseSwapRequest)) *MockRpcProvider_CreateAutoReverseSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Tenant
		if args[0] != nil {
			arg0 = args[0].(*database.Tenant)
		}
		var arg1 *lightzrpc.CreateReverseSwapRequest
		if args[1] != nil {
			arg1 = args[1].(*lightzrpc.CreateReverseSwapRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcProvider_CreateAutoReverseSwap_Call) Return(err error) *MockRpcProvider_CreateAutoReverseSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcProvider_CreateAutoReverseSwap_Call) RunAndReturn(run func(tenant *database.Tenant, request *lightzrpc.CreateReverseSwapRequest) error) *MockRpcProvider_CreateAutoReverseSwap_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAutoSwap provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) CreateAutoSwap(tenant *database.Tenant, request *lightzrpc.CreateSwapRequest) error {
	ret := _mock.Called(tenant, request)

	if len(ret) == 0 {
		panic("no return value specified for CreateAutoSwap")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.Tenant, *lightzrpc.CreateSwapRequest) error); ok {
		r0 = returnFunc(tenant, request)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRpcProvider_CreateAutoSwap_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAutoSwap'
type MockRpcProvider_CreateAutoSwap_Call struct {
	*mock.Call
}

// CreateAutoSwap is a helper method to define mock.On call
//   - tenant *database.Tenant
//   - request *lightzrpc.CreateSwapRequest
func (_e *MockRpcProvider_Expecter) CreateAutoSwap(tenant interface{}, request interface{}) *MockRpcProvider_CreateAutoSwap_Call {
	return &MockRpcProvider_CreateAutoSwap_Call{Call: _e.mock.On("CreateAutoSwap", tenant, request)}
}

func (_c *MockRpcProvider_CreateAutoSwap_Call) Run(run func(tenant *database.Tenant, request *lightzrpc.CreateSwapRequest)) *MockRpcProvider_CreateAutoSwap_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Tenant
		if args[0] != nil {
			arg0 = args[0].(*database.Tenant)
		}
		var arg1 *lightzrpc.CreateSwapRequest
		if args[1] != nil {
			arg1 = args[1].(*lightzrpc.CreateSwapRequest)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcProvider_CreateAutoSwap_Call) Return(err error) *MockRpcProvider_CreateAutoSwap_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRpcProvider_CreateAutoSwap_Call) RunAndReturn(run func(tenant *database.Tenant, request *lightzrpc.CreateSwapRequest) error) *MockRpcProvider_CreateAutoSwap_Call {
	_c.Call.Return(run)
	return _c
}

// GetAutoSwapPairInfo provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) GetAutoSwapPairInfo(swapType lightzrpc.SwapType, pair *lightzrpc.Pair) (*lightzrpc.PairInfo, error) {
	ret := _mock.Called(swapType, pair)

	if len(ret) == 0 {
		panic("no return value specified for GetAutoSwapPairInfo")
	}

	var r0 *lightzrpc.PairInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(lightzrpc.SwapType, *lightzrpc.Pair) (*lightzrpc.PairInfo, error)); ok {
		return returnFunc(swapType, pair)
	}
	if returnFunc, ok := ret.Get(0).(func(lightzrpc.SwapType, *lightzrpc.Pair) *lightzrpc.PairInfo); ok {
		r0 = returnFunc(swapType, pair)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lightzrpc.PairInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(lightzrpc.SwapType, *lightzrpc.Pair) error); ok {
		r1 = returnFunc(swapType, pair)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcProvider_GetAutoSwapPairInfo_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAutoSwapPairInfo'
type MockRpcProvider_GetAutoSwapPairInfo_Call struct {
	*mock.Call
}

// GetAutoSwapPairInfo is a helper method to define mock.On call
//   - swapType lightzrpc.SwapType
//   - pair *lightzrpc.Pair
func (_e *MockRpcProvider_Expecter) GetAutoSwapPairInfo(swapType interface{}, pair interface{}) *MockRpcProvider_GetAutoSwapPairInfo_Call {
	return &MockRpcProvider_GetAutoSwapPairInfo_Call{Call: _e.mock.On("GetAutoSwapPairInfo", swapType, pair)}
}

func (_c *MockRpcProvider_GetAutoSwapPairInfo_Call) Run(run func(swapType lightzrpc.SwapType, pair *lightzrpc.Pair)) *MockRpcProvider_GetAutoSwapPairInfo_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightzrpc.SwapType
		if args[0] != nil {
			arg0 = args[0].(lightzrpc.SwapType)
		}
		var arg1 *lightzrpc.Pair
		if args[1] != nil {
			arg1 = args[1].(*lightzrpc.Pair)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRpcProvider_GetAutoSwapPairInfo_Call) Return(pairInfo *lightzrpc.PairInfo, err error) *MockRpcProvider_GetAutoSwapPairInfo_Call {
	_c.Call.Return(pairInfo, err)
	return _c
}

func (_c *MockRpcProvider_GetAutoSwapPairInfo_Call) RunAndReturn(run func(swapType lightzrpc.SwapType, pair *lightzrpc.Pair) (*lightzrpc.PairInfo, error)) *MockRpcProvider_GetAutoSwapPairInfo_Call {
	_c.Call.Return(run)
	return _c
}

// GetBlockUpdates provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) GetBlockUpdates(currency lightz.Currency) (<-chan *onchain.BlockEpoch, func()) {
	ret := _mock.Called(currency)

	if len(ret) == 0 {
		panic("no return value specified for GetBlockUpdates")
	}

	var r0 <-chan *onchain.BlockEpoch
	var r1 func()
	if returnFunc, ok := ret.Get(0).(func(lightz.Currency) (<-chan *onchain.BlockEpoch, func())); ok {
		return returnFunc(currency)
	}
	if returnFunc, ok := ret.Get(0).(func(lightz.Currency) <-chan *onchain.BlockEpoch); ok {
		r0 = returnFunc(currency)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan *onchain.BlockEpoch)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(lightz.Currency) func()); ok {
		r1 = returnFunc(currency)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

// MockRpcProvider_GetBlockUpdates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBlockUpdates'
type MockRpcProvider_GetBlockUpdates_Call struct {
	*mock.Call
}

// GetBlockUpdates is a helper method to define mock.On call
//   - currency lightz.Currency
func (_e *MockRpcProvider_Expecter) GetBlockUpdates(currency interface{}) *MockRpcProvider_GetBlockUpdates_Call {
	return &MockRpcProvider_GetBlockUpdates_Call{Call: _e.mock.On("GetBlockUpdates", currency)}
}

func (_c *MockRpcProvider_GetBlockUpdates_Call) Run(run func(currency lightz.Currency)) *MockRpcProvider_GetBlockUpdates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 lightz.Currency
		if args[0] != nil {
			arg0 = args[0].(lightz.Currency)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcProvider_GetBlockUpdates_Call) Return(blockEpochCh <-chan *onchain.BlockEpoch, fn func()) *MockRpcProvider_GetBlockUpdates_Call {
	_c.Call.Return(blockEpochCh, fn)
	return _c
}

func (_c *MockRpcProvider_GetBlockUpdates_Call) RunAndReturn(run func(currency lightz.Currency) (<-chan *onchain.BlockEpoch, func())) *MockRpcProvider_GetBlockUpdates_Call {
	_c.Call.Return(run)
	return _c
}

// GetLightningChannels provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) GetLightningChannels() ([]*lightning.LightningChannel, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLightningChannels")
	}

	var r0 []*lightning.LightningChannel
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]*lightning.LightningChannel, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []*lightning.LightningChannel); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*lightning.LightningChannel)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcProvider_GetLightningChannels_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLightningChannels'
type MockRpcProvider_GetLightningChannels_Call struct {
	*mock.Call
}

// GetLightningChannels is a helper method to define mock.On call
func (_e *MockRpcProvider_Expecter) GetLightningChannels() *MockRpcProvider_GetLightningChannels_Call {
	return &MockRpcProvider_GetLightningChannels_Call{Call: _e.mock.On("GetLightningChannels")}
}

func (_c *MockRpcProvider_GetLightningChannels_Call) Run(run func()) *MockRpcProvider_GetLightningChannels_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRpcProvider_GetLightningChannels_Call) Return(lightningChannels []*lightning.LightningChannel, err error) *MockRpcProvider_GetLightningChannels_Call {
	_c.Call.Return(lightningChannels, err)
	return _c
}

func (_c *MockRpcProvider_GetLightningChannels_Call) RunAndReturn(run func() ([]*lightning.LightningChannel, error)) *MockRpcProvider_GetLightningChannels_Call {
	_c.Call.Return(run)
	return _c
}

// WalletSendFee provides a mock function for the type MockRpcProvider
func (_mock *MockRpcProvider) WalletSendFee(request *lightzrpc.WalletSendRequest) (*lightzrpc.WalletSendFee, error) {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for WalletSendFee")
	}

	var r0 *lightzrpc.WalletSendFee
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*lightzrpc.WalletSendRequest) (*lightzrpc.WalletSendFee, error)); ok {
		return returnFunc(request)
	}
	if returnFunc, ok := ret.Get(0).(func(*lightzrpc.WalletSendRequest) *lightzrpc.WalletSendFee); ok {
		r0 = returnFunc(request)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*lightzrpc.WalletSendFee)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*lightzrpc.WalletSendRequest) error); ok {
		r1 = returnFunc(request)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRpcProvider_WalletSendFee_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WalletSendFee'
type MockRpcProvider_WalletSendFee_Call struct {
	*mock.Call
}

// WalletSendFee is a helper method to define mock.On call
//   - request *lightzrpc.WalletSendRequest
func (_e *MockRpcProvider_Expecter) WalletSendFee(request interface{}) *MockRpcProvider_WalletSendFee_Call {
	return &MockRpcProvider_WalletSendFee_Call{Call: _e.mock.On("WalletSendFee", request)}
}

func (_c *MockRpcProvider_WalletSendFee_Call) Run(run func(request *lightzrpc.WalletSendRequest)) *MockRpcProvider_WalletSendFee_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *lightzrpc.WalletSendRequest
		if args[0] != nil {
			arg0 = args[0].(*lightzrpc.WalletSendRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRpcProvider_WalletSendFee_Call) Return(walletSendFee *lightzrpc.WalletSendFee, err error) *MockRpcProvider_WalletSendFee_Call {
	_c.Call.Return(walletSendFee, err)
	return _c
}

func (_c *MockRpcProvider_WalletSendFee_Call) RunAndReturn(run func(request *lightzrpc.WalletSendRequest) (*lightzrpc.WalletSendFee, error)) *MockRpcProvider_WalletSendFee_Call {
	_c.Call.Return(run)
	return _c
}
