// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.12.4
// source: lightzrpc.proto

package lightzrpc

import (
	context "context"
	empty "github.com/golang/protobuf/ptypes/empty"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Lightz_GetInfo_FullMethodName                = "/lightzrpc.Lightz/GetInfo"
	Lightz_GetServiceInfo_FullMethodName         = "/lightzrpc.Lightz/GetServiceInfo"
	Lightz_GetPairInfo_FullMethodName            = "/lightzrpc.Lightz/GetPairInfo"
	Lightz_GetPairs_FullMethodName               = "/lightzrpc.Lightz/GetPairs"
	Lightz_ListSwaps_FullMethodName              = "/lightzrpc.Lightz/ListSwaps"
	Lightz_GetStats_FullMethodName               = "/lightzrpc.Lightz/GetStats"
	Lightz_RefundSwap_FullMethodName             = "/lightzrpc.Lightz/RefundSwap"
	Lightz_ClaimSwaps_FullMethodName             = "/lightzrpc.Lightz/ClaimSwaps"
	Lightz_GetSwapInfo_FullMethodName            = "/lightzrpc.Lightz/GetSwapInfo"
	Lightz_GetSwapInfoStream_FullMethodName      = "/lightzrpc.Lightz/GetSwapInfoStream"
	Lightz_Deposit_FullMethodName                = "/lightzrpc.Lightz/Deposit"
	Lightz_CreateSwap_FullMethodName             = "/lightzrpc.Lightz/CreateSwap"
	Lightz_CreateChannel_FullMethodName          = "/lightzrpc.Lightz/CreateChannel"
	Lightz_CreateReverseSwap_FullMethodName      = "/lightzrpc.Lightz/CreateReverseSwap"
	Lightz_CreateChainSwap_FullMethodName        = "/lightzrpc.Lightz/CreateChainSwap"
	Lightz_CreateWallet_FullMethodName           = "/lightzrpc.Lightz/CreateWallet"
	Lightz_ImportWallet_FullMethodName           = "/lightzrpc.Lightz/ImportWallet"
	Lightz_SetSubaccount_FullMethodName          = "/lightzrpc.Lightz/SetSubaccount"
	Lightz_GetSubaccounts_FullMethodName         = "/lightzrpc.Lightz/GetSubaccounts"
	Lightz_GetWallets_FullMethodName             = "/lightzrpc.Lightz/GetWallets"
	Lightz_GetWallet_FullMethodName              = "/lightzrpc.Lightz/GetWallet"
	Lightz_GetWalletSendFee_FullMethodName       = "/lightzrpc.Lightz/GetWalletSendFee"
	Lightz_ListWalletTransactions_FullMethodName = "/lightzrpc.Lightz/ListWalletTransactions"
	Lightz_BumpTransaction_FullMethodName        = "/lightzrpc.Lightz/BumpTransaction"
	Lightz_GetWalletCredentials_FullMethodName   = "/lightzrpc.Lightz/GetWalletCredentials"
	Lightz_RemoveWallet_FullMethodName           = "/lightzrpc.Lightz/RemoveWallet"
	Lightz_WalletSend_FullMethodName             = "/lightzrpc.Lightz/WalletSend"
	Lightz_WalletReceive_FullMethodName          = "/lightzrpc.Lightz/WalletReceive"
	Lightz_Stop_FullMethodName                   = "/lightzrpc.Lightz/Stop"
	Lightz_Unlock_FullMethodName                 = "/lightzrpc.Lightz/Unlock"
	Lightz_VerifyWalletPassword_FullMethodName   = "/lightzrpc.Lightz/VerifyWalletPassword"
	Lightz_ChangeWalletPassword_FullMethodName   = "/lightzrpc.Lightz/ChangeWalletPassword"
	Lightz_CreateTenant_FullMethodName           = "/lightzrpc.Lightz/CreateTenant"
	Lightz_ListTenants_FullMethodName            = "/lightzrpc.Lightz/ListTenants"
	Lightz_GetTenant_FullMethodName              = "/lightzrpc.Lightz/GetTenant"
	Lightz_RemoveTenant_FullMethodName           = "/lightzrpc.Lightz/RemoveTenant"
	Lightz_BakeMacaroon_FullMethodName           = "/lightzrpc.Lightz/BakeMacaroon"
	Lightz_GetSwapMnemonic_FullMethodName        = "/lightzrpc.Lightz/GetSwapMnemonic"
	Lightz_SetSwapMnemonic_FullMethodName        = "/lightzrpc.Lightz/SetSwapMnemonic"
)

// LightzClient is the client API for Lightz service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type LightzClient interface {
	// Gets general information about the daemon like the chain of the lightning node it is connected to
	// and the IDs of pending swaps.
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// Deprecated: Do not use.
	//
	// Fetches the latest limits and fees from the Lightz backend API it is connected to.
	GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error)
	// Fetches information about a specific pair for a chain swap.
	GetPairInfo(ctx context.Context, in *GetPairInfoRequest, opts ...grpc.CallOption) (*PairInfo, error)
	// Fetches all available pairs for submarine and reverse swaps.
	GetPairs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetPairsResponse, error)
	// Returns a list of all swaps, reverse swaps, and chain swaps in the database.
	ListSwaps(ctx context.Context, in *ListSwapsRequest, opts ...grpc.CallOption) (*ListSwapsResponse, error)
	// Returns stats of all swaps, reverse swaps, and chain swaps in the database.
	GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error)
	// Refund a failed swap manually.
	// This is only required when no refund address has been set and the swap does not have an associated wallet.
	RefundSwap(ctx context.Context, in *RefundSwapRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error)
	// Claim swaps manually.
	// This is only required when no claim address has been set and the swap does not have an associated wallet.
	ClaimSwaps(ctx context.Context, in *ClaimSwapsRequest, opts ...grpc.CallOption) (*ClaimSwapsResponse, error)
	// Gets all available information about a swap from the database.
	GetSwapInfo(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error)
	// Returns the entire history of the swap if is still pending and streams updates in real time.
	// If the swap id is empty or "*" updates for all swaps will be streamed.
	GetSwapInfoStream(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSwapInfoResponse], error)
	// Deprecated: Do not use.
	//
	// This is a wrapper for channel creation swaps. The daemon only returns the ID, timeout block height and lockup address.
	// The Lightz backend takes care of the rest. When an amount of onchain coins that is in the limits is sent to the address
	// before the timeout block height, the daemon creates a new lightning invoice, sends it to the Lightz backend which
	// will try to pay it and if that is not possible, create a new channel to make the swap succeed.
	Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error)
	// Creates a new swap from onchain to lightning.
	CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error)
	// Deprecated: Do not use.
	//
	// Create a new swap from onchain to a new lightning channel. The daemon will only accept the invoice payment if the HTLCs
	// is coming trough a new channel channel opened by Lightz.
	CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error)
	// Creates a new reverse swap from lightning to onchain. If `accept_zero_conf` is set to true in the request, the daemon
	// will not wait until the lockup transaction from Lightz is confirmed in a block, but will claim it instantly.
	CreateReverseSwap(ctx context.Context, in *CreateReverseSwapRequest, opts ...grpc.CallOption) (*CreateReverseSwapResponse, error)
	// Creates a new chain swap from one chain to another. If `accept_zero_conf` is set to true in the request, the daemon
	// will not wait until the lockup transaction from Lightz is confirmed in a block, but will claim it instantly.
	CreateChainSwap(ctx context.Context, in *CreateChainSwapRequest, opts ...grpc.CallOption) (*ChainSwapInfo, error)
	// Creates a new liquid wallet and returns the mnemonic.
	CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error)
	// Imports an existing wallet.
	ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*Wallet, error)
	// Deprecated: Do not use.
	//
	// Sets the subaccount of a wallet. Not supported for readonly wallets.
	SetSubaccount(ctx context.Context, in *SetSubaccountRequest, opts ...grpc.CallOption) (*Subaccount, error)
	// Deprecated: Do not use.
	//
	// Returns all subaccounts for a given wallet. Not supported for readonly wallets.
	GetSubaccounts(ctx context.Context, in *GetSubaccountsRequest, opts ...grpc.CallOption) (*GetSubaccountsResponse, error)
	// Returns all available wallets.
	GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*Wallets, error)
	// Returns the current balance and subaccount of a wallet.
	GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error)
	// Calculates the fee for an equivalent `WalletSend` request.
	// If `address` is left empty, a dummy swap address will be used, allowing for a fee estimation of a swap lockup transaction.
	GetWalletSendFee(ctx context.Context, in *WalletSendRequest, opts ...grpc.CallOption) (*WalletSendFee, error)
	// Returns recent transactions from a wallet.
	ListWalletTransactions(ctx context.Context, in *ListWalletTransactionsRequest, opts ...grpc.CallOption) (*ListWalletTransactionsResponse, error)
	// Increase the fee of a transaction using RBF.
	// The transaction has to belong to one of the clients wallets.
	BumpTransaction(ctx context.Context, in *BumpTransactionRequest, opts ...grpc.CallOption) (*BumpTransactionResponse, error)
	// Returns the credentials of a wallet. The password will be required if the wallet is encrypted.
	GetWalletCredentials(ctx context.Context, in *GetWalletCredentialsRequest, opts ...grpc.CallOption) (*WalletCredentials, error)
	// Removes a wallet.
	RemoveWallet(ctx context.Context, in *RemoveWalletRequest, opts ...grpc.CallOption) (*RemoveWalletResponse, error)
	// Send coins from a wallet. Only the confirmed balance can be spent.
	WalletSend(ctx context.Context, in *WalletSendRequest, opts ...grpc.CallOption) (*WalletSendResponse, error)
	// Get a new address of the wallet.
	WalletReceive(ctx context.Context, in *WalletReceiveRequest, opts ...grpc.CallOption) (*WalletReceiveResponse, error)
	// Gracefully stops the daemon.
	Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error)
	// Unlocks the server. This will be required on startup if there are any encrypted wallets.
	Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Check if the password is correct.
	VerifyWalletPassword(ctx context.Context, in *VerifyWalletPasswordRequest, opts ...grpc.CallOption) (*VerifyWalletPasswordResponse, error)
	// Changes the password for wallet encryption.
	ChangeWalletPassword(ctx context.Context, in *ChangeWalletPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Creates a new tenant which can be used to bake restricted macaroons.
	CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Returns all tenants.
	ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error)
	// Get a specific tenant.
	GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error)
	// Removes a tenant. Only allowed if the tenant has no associated wallets.
	RemoveTenant(ctx context.Context, in *RemoveTenantRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	// Bakes a new macaroon with the specified permissions.
	// The macaroon can also be restricted to a specific tenant. In this case,
	// - any swap or wallet created with the returned macaroon will belong to this tenant and can not be accessed by other tenants.
	// - the lightning node connected to the daemon can not be used to pay or create invoices for swaps.
	BakeMacaroon(ctx context.Context, in *BakeMacaroonRequest, opts ...grpc.CallOption) (*BakeMacaroonResponse, error)
	// Returns mnemonic used for the key derivation of swaps, which can be used to restore swap information in the case of data loss.
	GetSwapMnemonic(ctx context.Context, in *GetSwapMnemonicRequest, opts ...grpc.CallOption) (*GetSwapMnemonicResponse, error)
	// Sets the mnemonic used for key derivation of swaps. An existing mnemonic can be used, or a new one can be generated.
	SetSwapMnemonic(ctx context.Context, in *SetSwapMnemonicRequest, opts ...grpc.CallOption) (*SetSwapMnemonicResponse, error)
}

type lightzClient struct {
	cc grpc.ClientConnInterface
}

func NewLightzClient(cc grpc.ClientConnInterface) LightzClient {
	return &lightzClient{cc}
}

func (c *lightzClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, Lightz_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *lightzClient) GetServiceInfo(ctx context.Context, in *GetServiceInfoRequest, opts ...grpc.CallOption) (*GetServiceInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceInfoResponse)
	err := c.cc.Invoke(ctx, Lightz_GetServiceInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetPairInfo(ctx context.Context, in *GetPairInfoRequest, opts ...grpc.CallOption) (*PairInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PairInfo)
	err := c.cc.Invoke(ctx, Lightz_GetPairInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetPairs(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*GetPairsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPairsResponse)
	err := c.cc.Invoke(ctx, Lightz_GetPairs_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ListSwaps(ctx context.Context, in *ListSwapsRequest, opts ...grpc.CallOption) (*ListSwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSwapsResponse)
	err := c.cc.Invoke(ctx, Lightz_ListSwaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetStats(ctx context.Context, in *GetStatsRequest, opts ...grpc.CallOption) (*GetStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatsResponse)
	err := c.cc.Invoke(ctx, Lightz_GetStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) RefundSwap(ctx context.Context, in *RefundSwapRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwapInfoResponse)
	err := c.cc.Invoke(ctx, Lightz_RefundSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ClaimSwaps(ctx context.Context, in *ClaimSwapsRequest, opts ...grpc.CallOption) (*ClaimSwapsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimSwapsResponse)
	err := c.cc.Invoke(ctx, Lightz_ClaimSwaps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetSwapInfo(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (*GetSwapInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwapInfoResponse)
	err := c.cc.Invoke(ctx, Lightz_GetSwapInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetSwapInfoStream(ctx context.Context, in *GetSwapInfoRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetSwapInfoResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Lightz_ServiceDesc.Streams[0], Lightz_GetSwapInfoStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetSwapInfoRequest, GetSwapInfoResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lightz_GetSwapInfoStreamClient = grpc.ServerStreamingClient[GetSwapInfoResponse]

// Deprecated: Do not use.
func (c *lightzClient) Deposit(ctx context.Context, in *DepositRequest, opts ...grpc.CallOption) (*DepositResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DepositResponse)
	err := c.cc.Invoke(ctx, Lightz_Deposit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) CreateSwap(ctx context.Context, in *CreateSwapRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSwapResponse)
	err := c.cc.Invoke(ctx, Lightz_CreateSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *lightzClient) CreateChannel(ctx context.Context, in *CreateChannelRequest, opts ...grpc.CallOption) (*CreateSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSwapResponse)
	err := c.cc.Invoke(ctx, Lightz_CreateChannel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) CreateReverseSwap(ctx context.Context, in *CreateReverseSwapRequest, opts ...grpc.CallOption) (*CreateReverseSwapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateReverseSwapResponse)
	err := c.cc.Invoke(ctx, Lightz_CreateReverseSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) CreateChainSwap(ctx context.Context, in *CreateChainSwapRequest, opts ...grpc.CallOption) (*ChainSwapInfo, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChainSwapInfo)
	err := c.cc.Invoke(ctx, Lightz_CreateChainSwap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) CreateWallet(ctx context.Context, in *CreateWalletRequest, opts ...grpc.CallOption) (*CreateWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateWalletResponse)
	err := c.cc.Invoke(ctx, Lightz_CreateWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ImportWallet(ctx context.Context, in *ImportWalletRequest, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, Lightz_ImportWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *lightzClient) SetSubaccount(ctx context.Context, in *SetSubaccountRequest, opts ...grpc.CallOption) (*Subaccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Subaccount)
	err := c.cc.Invoke(ctx, Lightz_SetSubaccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Deprecated: Do not use.
func (c *lightzClient) GetSubaccounts(ctx context.Context, in *GetSubaccountsRequest, opts ...grpc.CallOption) (*GetSubaccountsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSubaccountsResponse)
	err := c.cc.Invoke(ctx, Lightz_GetSubaccounts_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetWallets(ctx context.Context, in *GetWalletsRequest, opts ...grpc.CallOption) (*Wallets, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallets)
	err := c.cc.Invoke(ctx, Lightz_GetWallets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetWallet(ctx context.Context, in *GetWalletRequest, opts ...grpc.CallOption) (*Wallet, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Wallet)
	err := c.cc.Invoke(ctx, Lightz_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetWalletSendFee(ctx context.Context, in *WalletSendRequest, opts ...grpc.CallOption) (*WalletSendFee, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletSendFee)
	err := c.cc.Invoke(ctx, Lightz_GetWalletSendFee_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ListWalletTransactions(ctx context.Context, in *ListWalletTransactionsRequest, opts ...grpc.CallOption) (*ListWalletTransactionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWalletTransactionsResponse)
	err := c.cc.Invoke(ctx, Lightz_ListWalletTransactions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) BumpTransaction(ctx context.Context, in *BumpTransactionRequest, opts ...grpc.CallOption) (*BumpTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BumpTransactionResponse)
	err := c.cc.Invoke(ctx, Lightz_BumpTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetWalletCredentials(ctx context.Context, in *GetWalletCredentialsRequest, opts ...grpc.CallOption) (*WalletCredentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletCredentials)
	err := c.cc.Invoke(ctx, Lightz_GetWalletCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) RemoveWallet(ctx context.Context, in *RemoveWalletRequest, opts ...grpc.CallOption) (*RemoveWalletResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWalletResponse)
	err := c.cc.Invoke(ctx, Lightz_RemoveWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) WalletSend(ctx context.Context, in *WalletSendRequest, opts ...grpc.CallOption) (*WalletSendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletSendResponse)
	err := c.cc.Invoke(ctx, Lightz_WalletSend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) WalletReceive(ctx context.Context, in *WalletReceiveRequest, opts ...grpc.CallOption) (*WalletReceiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WalletReceiveResponse)
	err := c.cc.Invoke(ctx, Lightz_WalletReceive_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) Stop(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Lightz_Stop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) Unlock(ctx context.Context, in *UnlockRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Lightz_Unlock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) VerifyWalletPassword(ctx context.Context, in *VerifyWalletPasswordRequest, opts ...grpc.CallOption) (*VerifyWalletPasswordResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyWalletPasswordResponse)
	err := c.cc.Invoke(ctx, Lightz_VerifyWalletPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ChangeWalletPassword(ctx context.Context, in *ChangeWalletPasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Lightz_ChangeWalletPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) CreateTenant(ctx context.Context, in *CreateTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, Lightz_CreateTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) ListTenants(ctx context.Context, in *ListTenantsRequest, opts ...grpc.CallOption) (*ListTenantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTenantsResponse)
	err := c.cc.Invoke(ctx, Lightz_ListTenants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetTenant(ctx context.Context, in *GetTenantRequest, opts ...grpc.CallOption) (*Tenant, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Tenant)
	err := c.cc.Invoke(ctx, Lightz_GetTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) RemoveTenant(ctx context.Context, in *RemoveTenantRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, Lightz_RemoveTenant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) BakeMacaroon(ctx context.Context, in *BakeMacaroonRequest, opts ...grpc.CallOption) (*BakeMacaroonResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BakeMacaroonResponse)
	err := c.cc.Invoke(ctx, Lightz_BakeMacaroon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) GetSwapMnemonic(ctx context.Context, in *GetSwapMnemonicRequest, opts ...grpc.CallOption) (*GetSwapMnemonicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSwapMnemonicResponse)
	err := c.cc.Invoke(ctx, Lightz_GetSwapMnemonic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *lightzClient) SetSwapMnemonic(ctx context.Context, in *SetSwapMnemonicRequest, opts ...grpc.CallOption) (*SetSwapMnemonicResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetSwapMnemonicResponse)
	err := c.cc.Invoke(ctx, Lightz_SetSwapMnemonic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// LightzServer is the server API for Lightz service.
// All implementations must embed UnimplementedLightzServer
// for forward compatibility.
type LightzServer interface {
	// Gets general information about the daemon like the chain of the lightning node it is connected to
	// and the IDs of pending swaps.
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// Deprecated: Do not use.
	//
	// Fetches the latest limits and fees from the Lightz backend API it is connected to.
	GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error)
	// Fetches information about a specific pair for a chain swap.
	GetPairInfo(context.Context, *GetPairInfoRequest) (*PairInfo, error)
	// Fetches all available pairs for submarine and reverse swaps.
	GetPairs(context.Context, *empty.Empty) (*GetPairsResponse, error)
	// Returns a list of all swaps, reverse swaps, and chain swaps in the database.
	ListSwaps(context.Context, *ListSwapsRequest) (*ListSwapsResponse, error)
	// Returns stats of all swaps, reverse swaps, and chain swaps in the database.
	GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error)
	// Refund a failed swap manually.
	// This is only required when no refund address has been set and the swap does not have an associated wallet.
	RefundSwap(context.Context, *RefundSwapRequest) (*GetSwapInfoResponse, error)
	// Claim swaps manually.
	// This is only required when no claim address has been set and the swap does not have an associated wallet.
	ClaimSwaps(context.Context, *ClaimSwapsRequest) (*ClaimSwapsResponse, error)
	// Gets all available information about a swap from the database.
	GetSwapInfo(context.Context, *GetSwapInfoRequest) (*GetSwapInfoResponse, error)
	// Returns the entire history of the swap if is still pending and streams updates in real time.
	// If the swap id is empty or "*" updates for all swaps will be streamed.
	GetSwapInfoStream(*GetSwapInfoRequest, grpc.ServerStreamingServer[GetSwapInfoResponse]) error
	// Deprecated: Do not use.
	//
	// This is a wrapper for channel creation swaps. The daemon only returns the ID, timeout block height and lockup address.
	// The Lightz backend takes care of the rest. When an amount of onchain coins that is in the limits is sent to the address
	// before the timeout block height, the daemon creates a new lightning invoice, sends it to the Lightz backend which
	// will try to pay it and if that is not possible, create a new channel to make the swap succeed.
	Deposit(context.Context, *DepositRequest) (*DepositResponse, error)
	// Creates a new swap from onchain to lightning.
	CreateSwap(context.Context, *CreateSwapRequest) (*CreateSwapResponse, error)
	// Deprecated: Do not use.
	//
	// Create a new swap from onchain to a new lightning channel. The daemon will only accept the invoice payment if the HTLCs
	// is coming trough a new channel channel opened by Lightz.
	CreateChannel(context.Context, *CreateChannelRequest) (*CreateSwapResponse, error)
	// Creates a new reverse swap from lightning to onchain. If `accept_zero_conf` is set to true in the request, the daemon
	// will not wait until the lockup transaction from Lightz is confirmed in a block, but will claim it instantly.
	CreateReverseSwap(context.Context, *CreateReverseSwapRequest) (*CreateReverseSwapResponse, error)
	// Creates a new chain swap from one chain to another. If `accept_zero_conf` is set to true in the request, the daemon
	// will not wait until the lockup transaction from Lightz is confirmed in a block, but will claim it instantly.
	CreateChainSwap(context.Context, *CreateChainSwapRequest) (*ChainSwapInfo, error)
	// Creates a new liquid wallet and returns the mnemonic.
	CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error)
	// Imports an existing wallet.
	ImportWallet(context.Context, *ImportWalletRequest) (*Wallet, error)
	// Deprecated: Do not use.
	//
	// Sets the subaccount of a wallet. Not supported for readonly wallets.
	SetSubaccount(context.Context, *SetSubaccountRequest) (*Subaccount, error)
	// Deprecated: Do not use.
	//
	// Returns all subaccounts for a given wallet. Not supported for readonly wallets.
	GetSubaccounts(context.Context, *GetSubaccountsRequest) (*GetSubaccountsResponse, error)
	// Returns all available wallets.
	GetWallets(context.Context, *GetWalletsRequest) (*Wallets, error)
	// Returns the current balance and subaccount of a wallet.
	GetWallet(context.Context, *GetWalletRequest) (*Wallet, error)
	// Calculates the fee for an equivalent `WalletSend` request.
	// If `address` is left empty, a dummy swap address will be used, allowing for a fee estimation of a swap lockup transaction.
	GetWalletSendFee(context.Context, *WalletSendRequest) (*WalletSendFee, error)
	// Returns recent transactions from a wallet.
	ListWalletTransactions(context.Context, *ListWalletTransactionsRequest) (*ListWalletTransactionsResponse, error)
	// Increase the fee of a transaction using RBF.
	// The transaction has to belong to one of the clients wallets.
	BumpTransaction(context.Context, *BumpTransactionRequest) (*BumpTransactionResponse, error)
	// Returns the credentials of a wallet. The password will be required if the wallet is encrypted.
	GetWalletCredentials(context.Context, *GetWalletCredentialsRequest) (*WalletCredentials, error)
	// Removes a wallet.
	RemoveWallet(context.Context, *RemoveWalletRequest) (*RemoveWalletResponse, error)
	// Send coins from a wallet. Only the confirmed balance can be spent.
	WalletSend(context.Context, *WalletSendRequest) (*WalletSendResponse, error)
	// Get a new address of the wallet.
	WalletReceive(context.Context, *WalletReceiveRequest) (*WalletReceiveResponse, error)
	// Gracefully stops the daemon.
	Stop(context.Context, *empty.Empty) (*empty.Empty, error)
	// Unlocks the server. This will be required on startup if there are any encrypted wallets.
	Unlock(context.Context, *UnlockRequest) (*empty.Empty, error)
	// Check if the password is correct.
	VerifyWalletPassword(context.Context, *VerifyWalletPasswordRequest) (*VerifyWalletPasswordResponse, error)
	// Changes the password for wallet encryption.
	ChangeWalletPassword(context.Context, *ChangeWalletPasswordRequest) (*empty.Empty, error)
	// Creates a new tenant which can be used to bake restricted macaroons.
	CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error)
	// Returns all tenants.
	ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error)
	// Get a specific tenant.
	GetTenant(context.Context, *GetTenantRequest) (*Tenant, error)
	// Removes a tenant. Only allowed if the tenant has no associated wallets.
	RemoveTenant(context.Context, *RemoveTenantRequest) (*empty.Empty, error)
	// Bakes a new macaroon with the specified permissions.
	// The macaroon can also be restricted to a specific tenant. In this case,
	// - any swap or wallet created with the returned macaroon will belong to this tenant and can not be accessed by other tenants.
	// - the lightning node connected to the daemon can not be used to pay or create invoices for swaps.
	BakeMacaroon(context.Context, *BakeMacaroonRequest) (*BakeMacaroonResponse, error)
	// Returns mnemonic used for the key derivation of swaps, which can be used to restore swap information in the case of data loss.
	GetSwapMnemonic(context.Context, *GetSwapMnemonicRequest) (*GetSwapMnemonicResponse, error)
	// Sets the mnemonic used for key derivation of swaps. An existing mnemonic can be used, or a new one can be generated.
	SetSwapMnemonic(context.Context, *SetSwapMnemonicRequest) (*SetSwapMnemonicResponse, error)
	mustEmbedUnimplementedLightzServer()
}

// UnimplementedLightzServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedLightzServer struct{}

func (UnimplementedLightzServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedLightzServer) GetServiceInfo(context.Context, *GetServiceInfoRequest) (*GetServiceInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceInfo not implemented")
}
func (UnimplementedLightzServer) GetPairInfo(context.Context, *GetPairInfoRequest) (*PairInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPairInfo not implemented")
}
func (UnimplementedLightzServer) GetPairs(context.Context, *empty.Empty) (*GetPairsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPairs not implemented")
}
func (UnimplementedLightzServer) ListSwaps(context.Context, *ListSwapsRequest) (*ListSwapsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListSwaps not implemented")
}
func (UnimplementedLightzServer) GetStats(context.Context, *GetStatsRequest) (*GetStatsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetStats not implemented")
}
func (UnimplementedLightzServer) RefundSwap(context.Context, *RefundSwapRequest) (*GetSwapInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RefundSwap not implemented")
}
func (UnimplementedLightzServer) ClaimSwaps(context.Context, *ClaimSwapsRequest) (*ClaimSwapsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimSwaps not implemented")
}
func (UnimplementedLightzServer) GetSwapInfo(context.Context, *GetSwapInfoRequest) (*GetSwapInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwapInfo not implemented")
}
func (UnimplementedLightzServer) GetSwapInfoStream(*GetSwapInfoRequest, grpc.ServerStreamingServer[GetSwapInfoResponse]) error {
	return status.Error(codes.Unimplemented, "method GetSwapInfoStream not implemented")
}
func (UnimplementedLightzServer) Deposit(context.Context, *DepositRequest) (*DepositResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Deposit not implemented")
}
func (UnimplementedLightzServer) CreateSwap(context.Context, *CreateSwapRequest) (*CreateSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateSwap not implemented")
}
func (UnimplementedLightzServer) CreateChannel(context.Context, *CreateChannelRequest) (*CreateSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChannel not implemented")
}
func (UnimplementedLightzServer) CreateReverseSwap(context.Context, *CreateReverseSwapRequest) (*CreateReverseSwapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReverseSwap not implemented")
}
func (UnimplementedLightzServer) CreateChainSwap(context.Context, *CreateChainSwapRequest) (*ChainSwapInfo, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateChainSwap not implemented")
}
func (UnimplementedLightzServer) CreateWallet(context.Context, *CreateWalletRequest) (*CreateWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWallet not implemented")
}
func (UnimplementedLightzServer) ImportWallet(context.Context, *ImportWalletRequest) (*Wallet, error) {
	return nil, status.Error(codes.Unimplemented, "method ImportWallet not implemented")
}
func (UnimplementedLightzServer) SetSubaccount(context.Context, *SetSubaccountRequest) (*Subaccount, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSubaccount not implemented")
}
func (UnimplementedLightzServer) GetSubaccounts(context.Context, *GetSubaccountsRequest) (*GetSubaccountsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSubaccounts not implemented")
}
func (UnimplementedLightzServer) GetWallets(context.Context, *GetWalletsRequest) (*Wallets, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallets not implemented")
}
func (UnimplementedLightzServer) GetWallet(context.Context, *GetWalletRequest) (*Wallet, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedLightzServer) GetWalletSendFee(context.Context, *WalletSendRequest) (*WalletSendFee, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletSendFee not implemented")
}
func (UnimplementedLightzServer) ListWalletTransactions(context.Context, *ListWalletTransactionsRequest) (*ListWalletTransactionsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWalletTransactions not implemented")
}
func (UnimplementedLightzServer) BumpTransaction(context.Context, *BumpTransactionRequest) (*BumpTransactionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BumpTransaction not implemented")
}
func (UnimplementedLightzServer) GetWalletCredentials(context.Context, *GetWalletCredentialsRequest) (*WalletCredentials, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWalletCredentials not implemented")
}
func (UnimplementedLightzServer) RemoveWallet(context.Context, *RemoveWalletRequest) (*RemoveWalletResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWallet not implemented")
}
func (UnimplementedLightzServer) WalletSend(context.Context, *WalletSendRequest) (*WalletSendResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WalletSend not implemented")
}
func (UnimplementedLightzServer) WalletReceive(context.Context, *WalletReceiveRequest) (*WalletReceiveResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method WalletReceive not implemented")
}
func (UnimplementedLightzServer) Stop(context.Context, *empty.Empty) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Stop not implemented")
}
func (UnimplementedLightzServer) Unlock(context.Context, *UnlockRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Unlock not implemented")
}
func (UnimplementedLightzServer) VerifyWalletPassword(context.Context, *VerifyWalletPasswordRequest) (*VerifyWalletPasswordResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyWalletPassword not implemented")
}
func (UnimplementedLightzServer) ChangeWalletPassword(context.Context, *ChangeWalletPasswordRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeWalletPassword not implemented")
}
func (UnimplementedLightzServer) CreateTenant(context.Context, *CreateTenantRequest) (*Tenant, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateTenant not implemented")
}
func (UnimplementedLightzServer) ListTenants(context.Context, *ListTenantsRequest) (*ListTenantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTenants not implemented")
}
func (UnimplementedLightzServer) GetTenant(context.Context, *GetTenantRequest) (*Tenant, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTenant not implemented")
}
func (UnimplementedLightzServer) RemoveTenant(context.Context, *RemoveTenantRequest) (*empty.Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveTenant not implemented")
}
func (UnimplementedLightzServer) BakeMacaroon(context.Context, *BakeMacaroonRequest) (*BakeMacaroonResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BakeMacaroon not implemented")
}
func (UnimplementedLightzServer) GetSwapMnemonic(context.Context, *GetSwapMnemonicRequest) (*GetSwapMnemonicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSwapMnemonic not implemented")
}
func (UnimplementedLightzServer) SetSwapMnemonic(context.Context, *SetSwapMnemonicRequest) (*SetSwapMnemonicResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetSwapMnemonic not implemented")
}
func (UnimplementedLightzServer) mustEmbedUnimplementedLightzServer() {}
func (UnimplementedLightzServer) testEmbeddedByValue()                {}

// UnsafeLightzServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to LightzServer will
// result in compilation errors.
type UnsafeLightzServer interface {
	mustEmbedUnimplementedLightzServer()
}

func RegisterLightzServer(s grpc.ServiceRegistrar, srv LightzServer) {
	// If the following call panics, it indicates UnimplementedLightzServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Lightz_ServiceDesc, srv)
}

func _Lightz_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetServiceInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetServiceInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetServiceInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetServiceInfo(ctx, req.(*GetServiceInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetPairInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPairInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetPairInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetPairInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetPairInfo(ctx, req.(*GetPairInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetPairs_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetPairs(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetPairs_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetPairs(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ListSwaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ListSwaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ListSwaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ListSwaps(ctx, req.(*ListSwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetStats(ctx, req.(*GetStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_RefundSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RefundSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).RefundSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_RefundSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).RefundSwap(ctx, req.(*RefundSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ClaimSwaps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimSwapsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ClaimSwaps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ClaimSwaps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ClaimSwaps(ctx, req.(*ClaimSwapsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetSwapInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetSwapInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetSwapInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetSwapInfo(ctx, req.(*GetSwapInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetSwapInfoStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetSwapInfoRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(LightzServer).GetSwapInfoStream(m, &grpc.GenericServerStream[GetSwapInfoRequest, GetSwapInfoResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Lightz_GetSwapInfoStreamServer = grpc.ServerStreamingServer[GetSwapInfoResponse]

func _Lightz_Deposit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DepositRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).Deposit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_Deposit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).Deposit(ctx, req.(*DepositRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateSwap(ctx, req.(*CreateSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateChannel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChannelRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateChannel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateChannel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateChannel(ctx, req.(*CreateChannelRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateReverseSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReverseSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateReverseSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateReverseSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateReverseSwap(ctx, req.(*CreateReverseSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateChainSwap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateChainSwapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateChainSwap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateChainSwap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateChainSwap(ctx, req.(*CreateChainSwapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateWallet(ctx, req.(*CreateWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ImportWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ImportWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ImportWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ImportWallet(ctx, req.(*ImportWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_SetSubaccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSubaccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).SetSubaccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_SetSubaccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).SetSubaccount(ctx, req.(*SetSubaccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetSubaccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSubaccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetSubaccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetSubaccounts_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetSubaccounts(ctx, req.(*GetSubaccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetWallets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetWallets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetWallets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetWallets(ctx, req.(*GetWalletsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetWallet(ctx, req.(*GetWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetWalletSendFee_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetWalletSendFee(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetWalletSendFee_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetWalletSendFee(ctx, req.(*WalletSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ListWalletTransactions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWalletTransactionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ListWalletTransactions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ListWalletTransactions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ListWalletTransactions(ctx, req.(*ListWalletTransactionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_BumpTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BumpTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).BumpTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_BumpTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).BumpTransaction(ctx, req.(*BumpTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetWalletCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetWalletCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetWalletCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetWalletCredentials(ctx, req.(*GetWalletCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_RemoveWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWalletRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).RemoveWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_RemoveWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).RemoveWallet(ctx, req.(*RemoveWalletRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_WalletSend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletSendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).WalletSend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_WalletSend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).WalletSend(ctx, req.(*WalletSendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_WalletReceive_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalletReceiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).WalletReceive(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_WalletReceive_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).WalletReceive(ctx, req.(*WalletReceiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_Stop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).Stop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_Stop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).Stop(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_Unlock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).Unlock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_Unlock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).Unlock(ctx, req.(*UnlockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_VerifyWalletPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyWalletPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).VerifyWalletPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_VerifyWalletPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).VerifyWalletPassword(ctx, req.(*VerifyWalletPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ChangeWalletPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeWalletPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ChangeWalletPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ChangeWalletPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ChangeWalletPassword(ctx, req.(*ChangeWalletPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_CreateTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).CreateTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_CreateTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).CreateTenant(ctx, req.(*CreateTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_ListTenants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTenantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).ListTenants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_ListTenants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).ListTenants(ctx, req.(*ListTenantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetTenant(ctx, req.(*GetTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_RemoveTenant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTenantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).RemoveTenant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_RemoveTenant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).RemoveTenant(ctx, req.(*RemoveTenantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_BakeMacaroon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BakeMacaroonRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).BakeMacaroon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_BakeMacaroon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).BakeMacaroon(ctx, req.(*BakeMacaroonRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_GetSwapMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSwapMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).GetSwapMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_GetSwapMnemonic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).GetSwapMnemonic(ctx, req.(*GetSwapMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Lightz_SetSwapMnemonic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetSwapMnemonicRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(LightzServer).SetSwapMnemonic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Lightz_SetSwapMnemonic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(LightzServer).SetSwapMnemonic(ctx, req.(*SetSwapMnemonicRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Lightz_ServiceDesc is the grpc.ServiceDesc for Lightz service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Lightz_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "lightzrpc.Lightz",
	HandlerType: (*LightzServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _Lightz_GetInfo_Handler,
		},
		{
			MethodName: "GetServiceInfo",
			Handler:    _Lightz_GetServiceInfo_Handler,
		},
		{
			MethodName: "GetPairInfo",
			Handler:    _Lightz_GetPairInfo_Handler,
		},
		{
			MethodName: "GetPairs",
			Handler:    _Lightz_GetPairs_Handler,
		},
		{
			MethodName: "ListSwaps",
			Handler:    _Lightz_ListSwaps_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Lightz_GetStats_Handler,
		},
		{
			MethodName: "RefundSwap",
			Handler:    _Lightz_RefundSwap_Handler,
		},
		{
			MethodName: "ClaimSwaps",
			Handler:    _Lightz_ClaimSwaps_Handler,
		},
		{
			MethodName: "GetSwapInfo",
			Handler:    _Lightz_GetSwapInfo_Handler,
		},
		{
			MethodName: "Deposit",
			Handler:    _Lightz_Deposit_Handler,
		},
		{
			MethodName: "CreateSwap",
			Handler:    _Lightz_CreateSwap_Handler,
		},
		{
			MethodName: "CreateChannel",
			Handler:    _Lightz_CreateChannel_Handler,
		},
		{
			MethodName: "CreateReverseSwap",
			Handler:    _Lightz_CreateReverseSwap_Handler,
		},
		{
			MethodName: "CreateChainSwap",
			Handler:    _Lightz_CreateChainSwap_Handler,
		},
		{
			MethodName: "CreateWallet",
			Handler:    _Lightz_CreateWallet_Handler,
		},
		{
			MethodName: "ImportWallet",
			Handler:    _Lightz_ImportWallet_Handler,
		},
		{
			MethodName: "SetSubaccount",
			Handler:    _Lightz_SetSubaccount_Handler,
		},
		{
			MethodName: "GetSubaccounts",
			Handler:    _Lightz_GetSubaccounts_Handler,
		},
		{
			MethodName: "GetWallets",
			Handler:    _Lightz_GetWallets_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _Lightz_GetWallet_Handler,
		},
		{
			MethodName: "GetWalletSendFee",
			Handler:    _Lightz_GetWalletSendFee_Handler,
		},
		{
			MethodName: "ListWalletTransactions",
			Handler:    _Lightz_ListWalletTransactions_Handler,
		},
		{
			MethodName: "BumpTransaction",
			Handler:    _Lightz_BumpTransaction_Handler,
		},
		{
			MethodName: "GetWalletCredentials",
			Handler:    _Lightz_GetWalletCredentials_Handler,
		},
		{
			MethodName: "RemoveWallet",
			Handler:    _Lightz_RemoveWallet_Handler,
		},
		{
			MethodName: "WalletSend",
			Handler:    _Lightz_WalletSend_Handler,
		},
		{
			MethodName: "WalletReceive",
			Handler:    _Lightz_WalletReceive_Handler,
		},
		{
			MethodName: "Stop",
			Handler:    _Lightz_Stop_Handler,
		},
		{
			MethodName: "Unlock",
			Handler:    _Lightz_Unlock_Handler,
		},
		{
			MethodName: "VerifyWalletPassword",
			Handler:    _Lightz_VerifyWalletPassword_Handler,
		},
		{
			MethodName: "ChangeWalletPassword",
			Handler:    _Lightz_ChangeWalletPassword_Handler,
		},
		{
			MethodName: "CreateTenant",
			Handler:    _Lightz_CreateTenant_Handler,
		},
		{
			MethodName: "ListTenants",
			Handler:    _Lightz_ListTenants_Handler,
		},
		{
			MethodName: "GetTenant",
			Handler:    _Lightz_GetTenant_Handler,
		},
		{
			MethodName: "RemoveTenant",
			Handler:    _Lightz_RemoveTenant_Handler,
		},
		{
			MethodName: "BakeMacaroon",
			Handler:    _Lightz_BakeMacaroon_Handler,
		},
		{
			MethodName: "GetSwapMnemonic",
			Handler:    _Lightz_GetSwapMnemonic_Handler,
		},
		{
			MethodName: "SetSwapMnemonic",
			Handler:    _Lightz_SetSwapMnemonic_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetSwapInfoStream",
			Handler:       _Lightz_GetSwapInfoStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "lightzrpc.proto",
}
