// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.12.4
// source: autoswaprpc/autoswaprpc.proto

package autoswaprpc

import (
	empty "github.com/golang/protobuf/ptypes/empty"
	lightzrpc "github.com/lightzapp/lightz-client/pkg/lightzrpc"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetRecommendationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsRequest) Reset() {
	*x = GetRecommendationsRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsRequest) ProtoMessage() {}

func (x *GetRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*GetRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{0}
}

type LightningSwap struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Amount      uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeEstimate uint64                 `protobuf:"varint,2,opt,name=fee_estimate,json=feeEstimate,proto3" json:"fee_estimate,omitempty"`
	Type        lightzrpc.SwapType     `protobuf:"varint,3,opt,name=type,proto3,enum=lightzrpc.SwapType" json:"type,omitempty"`
	// Reasons for which the swap is not being executed
	DismissedReasons []string `protobuf:"bytes,4,rep,name=dismissed_reasons,json=dismissedReasons,proto3" json:"dismissed_reasons,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LightningSwap) Reset() {
	*x = LightningSwap{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightningSwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightningSwap) ProtoMessage() {}

func (x *LightningSwap) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightningSwap.ProtoReflect.Descriptor instead.
func (*LightningSwap) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{1}
}

func (x *LightningSwap) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *LightningSwap) GetFeeEstimate() uint64 {
	if x != nil {
		return x.FeeEstimate
	}
	return 0
}

func (x *LightningSwap) GetType() lightzrpc.SwapType {
	if x != nil {
		return x.Type
	}
	return lightzrpc.SwapType(0)
}

func (x *LightningSwap) GetDismissedReasons() []string {
	if x != nil {
		return x.DismissedReasons
	}
	return nil
}

type LightningThresholds struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Inbound       *uint64                `protobuf:"varint,1,opt,name=inbound,proto3,oneof" json:"inbound,omitempty"`
	Outbound      *uint64                `protobuf:"varint,2,opt,name=outbound,proto3,oneof" json:"outbound,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightningThresholds) Reset() {
	*x = LightningThresholds{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightningThresholds) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightningThresholds) ProtoMessage() {}

func (x *LightningThresholds) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightningThresholds.ProtoReflect.Descriptor instead.
func (*LightningThresholds) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{2}
}

func (x *LightningThresholds) GetInbound() uint64 {
	if x != nil && x.Inbound != nil {
		return *x.Inbound
	}
	return 0
}

func (x *LightningThresholds) GetOutbound() uint64 {
	if x != nil && x.Outbound != nil {
		return *x.Outbound
	}
	return 0
}

type LightningRecommendation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated when a swap is recommended for the associated `channel`,
	// otherwise, the current balances are below the configured thresholds
	Swap    *LightningSwap              `protobuf:"bytes,1,opt,name=swap,proto3,oneof" json:"swap,omitempty"`
	Channel *lightzrpc.LightningChannel `protobuf:"bytes,2,opt,name=channel,proto3" json:"channel,omitempty"`
	// the thresholds for a swap to be recommended for the `channel`
	Thresholds    *LightningThresholds `protobuf:"bytes,3,opt,name=thresholds,proto3" json:"thresholds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LightningRecommendation) Reset() {
	*x = LightningRecommendation{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightningRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightningRecommendation) ProtoMessage() {}

func (x *LightningRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightningRecommendation.ProtoReflect.Descriptor instead.
func (*LightningRecommendation) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{3}
}

func (x *LightningRecommendation) GetSwap() *LightningSwap {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *LightningRecommendation) GetChannel() *lightzrpc.LightningChannel {
	if x != nil {
		return x.Channel
	}
	return nil
}

func (x *LightningRecommendation) GetThresholds() *LightningThresholds {
	if x != nil {
		return x.Thresholds
	}
	return nil
}

type ChainSwap struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Amount      uint64                 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeEstimate uint64                 `protobuf:"varint,2,opt,name=fee_estimate,json=feeEstimate,proto3" json:"fee_estimate,omitempty"`
	// Reasons for which the swap is not being executed
	DismissedReasons []string `protobuf:"bytes,3,rep,name=dismissed_reasons,json=dismissedReasons,proto3" json:"dismissed_reasons,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChainSwap) Reset() {
	*x = ChainSwap{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainSwap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainSwap) ProtoMessage() {}

func (x *ChainSwap) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainSwap.ProtoReflect.Descriptor instead.
func (*ChainSwap) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{4}
}

func (x *ChainSwap) GetAmount() uint64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ChainSwap) GetFeeEstimate() uint64 {
	if x != nil {
		return x.FeeEstimate
	}
	return 0
}

func (x *ChainSwap) GetDismissedReasons() []string {
	if x != nil {
		return x.DismissedReasons
	}
	return nil
}

type ChainRecommendation struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Populated when a swap is recommended based on the configured `wallet_balance`
	// of the configured `from_wallet` exceeds the currently configured `max_balance`
	Swap          *ChainSwap         `protobuf:"bytes,1,opt,name=swap,proto3,oneof" json:"swap,omitempty"`
	WalletBalance *lightzrpc.Balance `protobuf:"bytes,2,opt,name=wallet_balance,json=walletBalance,proto3" json:"wallet_balance,omitempty"`
	MaxBalance    uint64             `protobuf:"varint,3,opt,name=max_balance,json=maxBalance,proto3" json:"max_balance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChainRecommendation) Reset() {
	*x = ChainRecommendation{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainRecommendation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainRecommendation) ProtoMessage() {}

func (x *ChainRecommendation) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainRecommendation.ProtoReflect.Descriptor instead.
func (*ChainRecommendation) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{5}
}

func (x *ChainRecommendation) GetSwap() *ChainSwap {
	if x != nil {
		return x.Swap
	}
	return nil
}

func (x *ChainRecommendation) GetWalletBalance() *lightzrpc.Balance {
	if x != nil {
		return x.WalletBalance
	}
	return nil
}

func (x *ChainRecommendation) GetMaxBalance() uint64 {
	if x != nil {
		return x.MaxBalance
	}
	return 0
}

type Budget struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         uint64                 `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Remaining     uint64                 `protobuf:"varint,2,opt,name=remaining,proto3" json:"remaining,omitempty"`
	StartDate     int64                  `protobuf:"varint,3,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"`
	EndDate       int64                  `protobuf:"varint,4,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`
	Stats         *lightzrpc.SwapStats   `protobuf:"bytes,5,opt,name=stats,proto3,oneof" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Budget) Reset() {
	*x = Budget{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Budget) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Budget) ProtoMessage() {}

func (x *Budget) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Budget.ProtoReflect.Descriptor instead.
func (*Budget) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{6}
}

func (x *Budget) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *Budget) GetRemaining() uint64 {
	if x != nil {
		return x.Remaining
	}
	return 0
}

func (x *Budget) GetStartDate() int64 {
	if x != nil {
		return x.StartDate
	}
	return 0
}

func (x *Budget) GetEndDate() int64 {
	if x != nil {
		return x.EndDate
	}
	return 0
}

func (x *Budget) GetStats() *lightzrpc.SwapStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

type GetRecommendationsResponse struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Lightning     []*LightningRecommendation `protobuf:"bytes,1,rep,name=lightning,proto3" json:"lightning,omitempty"`
	Chain         []*ChainRecommendation     `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRecommendationsResponse) Reset() {
	*x = GetRecommendationsResponse{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecommendationsResponse) ProtoMessage() {}

func (x *GetRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*GetRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{7}
}

func (x *GetRecommendationsResponse) GetLightning() []*LightningRecommendation {
	if x != nil {
		return x.Lightning
	}
	return nil
}

func (x *GetRecommendationsResponse) GetChain() []*ChainRecommendation {
	if x != nil {
		return x.Chain
	}
	return nil
}

type ExecuteRecommendationsRequest struct {
	state     protoimpl.MessageState     `protogen:"open.v1"`
	Lightning []*LightningRecommendation `protobuf:"bytes,1,rep,name=lightning,proto3" json:"lightning,omitempty"`
	Chain     []*ChainRecommendation     `protobuf:"bytes,2,rep,name=chain,proto3" json:"chain,omitempty"`
	// Forcefully execute all recommendations, even ones that have dismissal reasons.
	Force         *bool `protobuf:"varint,3,opt,name=force,proto3,oneof" json:"force,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRecommendationsRequest) Reset() {
	*x = ExecuteRecommendationsRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRecommendationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRecommendationsRequest) ProtoMessage() {}

func (x *ExecuteRecommendationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRecommendationsRequest.ProtoReflect.Descriptor instead.
func (*ExecuteRecommendationsRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteRecommendationsRequest) GetLightning() []*LightningRecommendation {
	if x != nil {
		return x.Lightning
	}
	return nil
}

func (x *ExecuteRecommendationsRequest) GetChain() []*ChainRecommendation {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *ExecuteRecommendationsRequest) GetForce() bool {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return false
}

type ExecuteRecommendationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteRecommendationsResponse) Reset() {
	*x = ExecuteRecommendationsResponse{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteRecommendationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteRecommendationsResponse) ProtoMessage() {}

func (x *ExecuteRecommendationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteRecommendationsResponse.ProtoReflect.Descriptor instead.
func (*ExecuteRecommendationsResponse) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{9}
}

type GetStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusRequest) Reset() {
	*x = GetStatusRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusRequest) ProtoMessage() {}

func (x *GetStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusRequest.ProtoReflect.Descriptor instead.
func (*GetStatusRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{10}
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Running       bool                   `protobuf:"varint,1,opt,name=running,proto3" json:"running,omitempty"`
	Error         *string                `protobuf:"bytes,2,opt,name=error,proto3,oneof" json:"error,omitempty"`
	Budget        *Budget                `protobuf:"bytes,3,opt,name=budget,proto3,oneof" json:"budget,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{11}
}

func (x *Status) GetRunning() bool {
	if x != nil {
		return x.Running
	}
	return false
}

func (x *Status) GetError() string {
	if x != nil && x.Error != nil {
		return *x.Error
	}
	return ""
}

func (x *Status) GetBudget() *Budget {
	if x != nil {
		return x.Budget
	}
	return nil
}

func (x *Status) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type GetStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Lightning     *Status                `protobuf:"bytes,1,opt,name=lightning,proto3,oneof" json:"lightning,omitempty"`
	Chain         *Status                `protobuf:"bytes,2,opt,name=chain,proto3,oneof" json:"chain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStatusResponse) Reset() {
	*x = GetStatusResponse{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStatusResponse) ProtoMessage() {}

func (x *GetStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStatusResponse.ProtoReflect.Descriptor instead.
func (*GetStatusResponse) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{12}
}

func (x *GetStatusResponse) GetLightning() *Status {
	if x != nil {
		return x.Lightning
	}
	return nil
}

func (x *GetStatusResponse) GetChain() *Status {
	if x != nil {
		return x.Chain
	}
	return nil
}

type GetConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConfigRequest) Reset() {
	*x = GetConfigRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConfigRequest) ProtoMessage() {}

func (x *GetConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConfigRequest.ProtoReflect.Descriptor instead.
func (*GetConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{13}
}

type UpdateLightningConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *LightningConfig       `protobuf:"bytes,1,opt,name=config,proto3,oneof" json:"config,omitempty"`
	FieldMask     *field_mask.FieldMask  `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3" json:"field_mask,omitempty"`
	Reset_        *bool                  `protobuf:"varint,3,opt,name=reset,proto3,oneof" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLightningConfigRequest) Reset() {
	*x = UpdateLightningConfigRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLightningConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLightningConfigRequest) ProtoMessage() {}

func (x *UpdateLightningConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLightningConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateLightningConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{14}
}

func (x *UpdateLightningConfigRequest) GetConfig() *LightningConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateLightningConfigRequest) GetFieldMask() *field_mask.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateLightningConfigRequest) GetReset_() bool {
	if x != nil && x.Reset_ != nil {
		return *x.Reset_
	}
	return false
}

type UpdateChainConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Config        *ChainConfig           `protobuf:"bytes,1,opt,name=config,proto3" json:"config,omitempty"`
	FieldMask     *field_mask.FieldMask  `protobuf:"bytes,2,opt,name=field_mask,json=fieldMask,proto3,oneof" json:"field_mask,omitempty"`
	Reset_        *bool                  `protobuf:"varint,3,opt,name=reset,proto3,oneof" json:"reset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChainConfigRequest) Reset() {
	*x = UpdateChainConfigRequest{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChainConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChainConfigRequest) ProtoMessage() {}

func (x *UpdateChainConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChainConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateChainConfigRequest) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{15}
}

func (x *UpdateChainConfigRequest) GetConfig() *ChainConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *UpdateChainConfigRequest) GetFieldMask() *field_mask.FieldMask {
	if x != nil {
		return x.FieldMask
	}
	return nil
}

func (x *UpdateChainConfigRequest) GetReset_() bool {
	if x != nil && x.Reset_ != nil {
		return *x.Reset_
	}
	return false
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chain         []*ChainConfig         `protobuf:"bytes,1,rep,name=chain,proto3" json:"chain,omitempty"`
	Lightning     []*LightningConfig     `protobuf:"bytes,2,rep,name=lightning,proto3" json:"lightning,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{16}
}

func (x *Config) GetChain() []*ChainConfig {
	if x != nil {
		return x.Chain
	}
	return nil
}

func (x *Config) GetLightning() []*LightningConfig {
	if x != nil {
		return x.Lightning
	}
	return nil
}

type ChainConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Enabled        bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	FromWallet     string                 `protobuf:"bytes,2,opt,name=from_wallet,json=fromWallet,proto3" json:"from_wallet,omitempty"`
	ToWallet       string                 `protobuf:"bytes,3,opt,name=to_wallet,json=toWallet,proto3" json:"to_wallet,omitempty"`
	ToAddress      string                 `protobuf:"bytes,4,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	MaxBalance     uint64                 `protobuf:"varint,5,opt,name=max_balance,json=maxBalance,proto3" json:"max_balance,omitempty"`
	ReserveBalance uint64                 `protobuf:"varint,10,opt,name=reserve_balance,json=reserveBalance,proto3" json:"reserve_balance,omitempty"`
	MaxFeePercent  float32                `protobuf:"fixed32,6,opt,name=max_fee_percent,json=maxFeePercent,proto3" json:"max_fee_percent,omitempty"`
	Budget         uint64                 `protobuf:"varint,7,opt,name=budget,proto3" json:"budget,omitempty"`
	BudgetInterval uint64                 `protobuf:"varint,8,opt,name=budget_interval,json=budgetInterval,proto3" json:"budget_interval,omitempty"`
	Tenant         *string                `protobuf:"bytes,9,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ChainConfig) Reset() {
	*x = ChainConfig{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChainConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChainConfig) ProtoMessage() {}

func (x *ChainConfig) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChainConfig.ProtoReflect.Descriptor instead.
func (*ChainConfig) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{17}
}

func (x *ChainConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *ChainConfig) GetFromWallet() string {
	if x != nil {
		return x.FromWallet
	}
	return ""
}

func (x *ChainConfig) GetToWallet() string {
	if x != nil {
		return x.ToWallet
	}
	return ""
}

func (x *ChainConfig) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *ChainConfig) GetMaxBalance() uint64 {
	if x != nil {
		return x.MaxBalance
	}
	return 0
}

func (x *ChainConfig) GetReserveBalance() uint64 {
	if x != nil {
		return x.ReserveBalance
	}
	return 0
}

func (x *ChainConfig) GetMaxFeePercent() float32 {
	if x != nil {
		return x.MaxFeePercent
	}
	return 0
}

func (x *ChainConfig) GetBudget() uint64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *ChainConfig) GetBudgetInterval() uint64 {
	if x != nil {
		return x.BudgetInterval
	}
	return 0
}

func (x *ChainConfig) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

type LightningConfig struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	Enabled                bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ChannelPollInterval    uint64                 `protobuf:"varint,2,opt,name=channel_poll_interval,json=channelPollInterval,proto3" json:"channel_poll_interval,omitempty"`
	StaticAddress          string                 `protobuf:"bytes,3,opt,name=static_address,json=staticAddress,proto3" json:"static_address,omitempty"`
	OutboundBalance        uint64                 `protobuf:"varint,4,opt,name=outbound_balance,json=outboundBalance,proto3" json:"outbound_balance,omitempty"`
	InboundBalance         uint64                 `protobuf:"varint,5,opt,name=inbound_balance,json=inboundBalance,proto3" json:"inbound_balance,omitempty"`
	OutboundBalancePercent float32                `protobuf:"fixed32,6,opt,name=outbound_balance_percent,json=outboundBalancePercent,proto3" json:"outbound_balance_percent,omitempty"`
	InboundBalancePercent  float32                `protobuf:"fixed32,7,opt,name=inbound_balance_percent,json=inboundBalancePercent,proto3" json:"inbound_balance_percent,omitempty"`
	MaxFeePercent          float32                `protobuf:"fixed32,8,opt,name=max_fee_percent,json=maxFeePercent,proto3" json:"max_fee_percent,omitempty"`
	AcceptZeroConf         bool                   `protobuf:"varint,9,opt,name=accept_zero_conf,json=acceptZeroConf,proto3" json:"accept_zero_conf,omitempty"`
	FailureBackoff         uint64                 `protobuf:"varint,10,opt,name=failure_backoff,json=failureBackoff,proto3" json:"failure_backoff,omitempty"`
	Budget                 uint64                 `protobuf:"varint,11,opt,name=budget,proto3" json:"budget,omitempty"`
	BudgetInterval         uint64                 `protobuf:"varint,12,opt,name=budget_interval,json=budgetInterval,proto3" json:"budget_interval,omitempty"`
	Currency               lightzrpc.Currency     `protobuf:"varint,13,opt,name=currency,proto3,enum=lightzrpc.Currency" json:"currency,omitempty"`
	SwapType               string                 `protobuf:"bytes,14,opt,name=swap_type,json=swapType,proto3" json:"swap_type,omitempty"`
	PerChannel             bool                   `protobuf:"varint,15,opt,name=per_channel,json=perChannel,proto3" json:"per_channel,omitempty"`
	Wallet                 string                 `protobuf:"bytes,16,opt,name=wallet,proto3" json:"wallet,omitempty"`
	MaxSwapAmount          uint64                 `protobuf:"varint,17,opt,name=max_swap_amount,json=maxSwapAmount,proto3" json:"max_swap_amount,omitempty"`
	Tenant                 *string                `protobuf:"bytes,18,opt,name=tenant,proto3,oneof" json:"tenant,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *LightningConfig) Reset() {
	*x = LightningConfig{}
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LightningConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LightningConfig) ProtoMessage() {}

func (x *LightningConfig) ProtoReflect() protoreflect.Message {
	mi := &file_autoswaprpc_autoswaprpc_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LightningConfig.ProtoReflect.Descriptor instead.
func (*LightningConfig) Descriptor() ([]byte, []int) {
	return file_autoswaprpc_autoswaprpc_proto_rawDescGZIP(), []int{18}
}

func (x *LightningConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *LightningConfig) GetChannelPollInterval() uint64 {
	if x != nil {
		return x.ChannelPollInterval
	}
	return 0
}

func (x *LightningConfig) GetStaticAddress() string {
	if x != nil {
		return x.StaticAddress
	}
	return ""
}

func (x *LightningConfig) GetOutboundBalance() uint64 {
	if x != nil {
		return x.OutboundBalance
	}
	return 0
}

func (x *LightningConfig) GetInboundBalance() uint64 {
	if x != nil {
		return x.InboundBalance
	}
	return 0
}

func (x *LightningConfig) GetOutboundBalancePercent() float32 {
	if x != nil {
		return x.OutboundBalancePercent
	}
	return 0
}

func (x *LightningConfig) GetInboundBalancePercent() float32 {
	if x != nil {
		return x.InboundBalancePercent
	}
	return 0
}

func (x *LightningConfig) GetMaxFeePercent() float32 {
	if x != nil {
		return x.MaxFeePercent
	}
	return 0
}

func (x *LightningConfig) GetAcceptZeroConf() bool {
	if x != nil {
		return x.AcceptZeroConf
	}
	return false
}

func (x *LightningConfig) GetFailureBackoff() uint64 {
	if x != nil {
		return x.FailureBackoff
	}
	return 0
}

func (x *LightningConfig) GetBudget() uint64 {
	if x != nil {
		return x.Budget
	}
	return 0
}

func (x *LightningConfig) GetBudgetInterval() uint64 {
	if x != nil {
		return x.BudgetInterval
	}
	return 0
}

func (x *LightningConfig) GetCurrency() lightzrpc.Currency {
	if x != nil {
		return x.Currency
	}
	return lightzrpc.Currency(0)
}

func (x *LightningConfig) GetSwapType() string {
	if x != nil {
		return x.SwapType
	}
	return ""
}

func (x *LightningConfig) GetPerChannel() bool {
	if x != nil {
		return x.PerChannel
	}
	return false
}

func (x *LightningConfig) GetWallet() string {
	if x != nil {
		return x.Wallet
	}
	return ""
}

func (x *LightningConfig) GetMaxSwapAmount() uint64 {
	if x != nil {
		return x.MaxSwapAmount
	}
	return 0
}

func (x *LightningConfig) GetTenant() string {
	if x != nil && x.Tenant != nil {
		return *x.Tenant
	}
	return ""
}

var File_autoswaprpc_autoswaprpc_proto protoreflect.FileDescriptor

const file_autoswaprpc_autoswaprpc_proto_rawDesc = "" +
	"\n" +
	"\x1dautoswaprpc/autoswaprpc.proto\x12\vautoswaprpc\x1a\x1bgoogle/protobuf/empty.proto\x1a google/protobuf/field_mask.proto\x1a\x0flightzrpc.proto\"\x1b\n" +
	"\x19GetRecommendationsRequest\"\xa0\x01\n" +
	"\rLightningSwap\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12!\n" +
	"\ffee_estimate\x18\x02 \x01(\x04R\vfeeEstimate\x12'\n" +
	"\x04type\x18\x03 \x01(\x0e2\x13.lightzrpc.SwapTypeR\x04type\x12+\n" +
	"\x11dismissed_reasons\x18\x04 \x03(\tR\x10dismissedReasons\"n\n" +
	"\x13LightningThresholds\x12\x1d\n" +
	"\ainbound\x18\x01 \x01(\x04H\x00R\ainbound\x88\x01\x01\x12\x1f\n" +
	"\boutbound\x18\x02 \x01(\x04H\x01R\boutbound\x88\x01\x01B\n" +
	"\n" +
	"\b_inboundB\v\n" +
	"\t_outbound\"\xd0\x01\n" +
	"\x17LightningRecommendation\x123\n" +
	"\x04swap\x18\x01 \x01(\v2\x1a.autoswaprpc.LightningSwapH\x00R\x04swap\x88\x01\x01\x125\n" +
	"\achannel\x18\x02 \x01(\v2\x1b.lightzrpc.LightningChannelR\achannel\x12@\n" +
	"\n" +
	"thresholds\x18\x03 \x01(\v2 .autoswaprpc.LightningThresholdsR\n" +
	"thresholdsB\a\n" +
	"\x05_swap\"s\n" +
	"\tChainSwap\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x04R\x06amount\x12!\n" +
	"\ffee_estimate\x18\x02 \x01(\x04R\vfeeEstimate\x12+\n" +
	"\x11dismissed_reasons\x18\x03 \x03(\tR\x10dismissedReasons\"\xab\x01\n" +
	"\x13ChainRecommendation\x12/\n" +
	"\x04swap\x18\x01 \x01(\v2\x16.autoswaprpc.ChainSwapH\x00R\x04swap\x88\x01\x01\x129\n" +
	"\x0ewallet_balance\x18\x02 \x01(\v2\x12.lightzrpc.BalanceR\rwalletBalance\x12\x1f\n" +
	"\vmax_balance\x18\x03 \x01(\x04R\n" +
	"maxBalanceB\a\n" +
	"\x05_swap\"\xb1\x01\n" +
	"\x06Budget\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x04R\x05total\x12\x1c\n" +
	"\tremaining\x18\x02 \x01(\x04R\tremaining\x12\x1d\n" +
	"\n" +
	"start_date\x18\x03 \x01(\x03R\tstartDate\x12\x19\n" +
	"\bend_date\x18\x04 \x01(\x03R\aendDate\x12/\n" +
	"\x05stats\x18\x05 \x01(\v2\x14.lightzrpc.SwapStatsH\x00R\x05stats\x88\x01\x01B\b\n" +
	"\x06_stats\"\x98\x01\n" +
	"\x1aGetRecommendationsResponse\x12B\n" +
	"\tlightning\x18\x01 \x03(\v2$.autoswaprpc.LightningRecommendationR\tlightning\x126\n" +
	"\x05chain\x18\x02 \x03(\v2 .autoswaprpc.ChainRecommendationR\x05chain\"\xc0\x01\n" +
	"\x1dExecuteRecommendationsRequest\x12B\n" +
	"\tlightning\x18\x01 \x03(\v2$.autoswaprpc.LightningRecommendationR\tlightning\x126\n" +
	"\x05chain\x18\x02 \x03(\v2 .autoswaprpc.ChainRecommendationR\x05chain\x12\x19\n" +
	"\x05force\x18\x03 \x01(\bH\x00R\x05force\x88\x01\x01B\b\n" +
	"\x06_force\" \n" +
	"\x1eExecuteRecommendationsResponse\"\x12\n" +
	"\x10GetStatusRequest\"\xa6\x01\n" +
	"\x06Status\x12\x18\n" +
	"\arunning\x18\x01 \x01(\bR\arunning\x12\x19\n" +
	"\x05error\x18\x02 \x01(\tH\x00R\x05error\x88\x01\x01\x120\n" +
	"\x06budget\x18\x03 \x01(\v2\x13.autoswaprpc.BudgetH\x01R\x06budget\x88\x01\x01\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescriptionB\b\n" +
	"\x06_errorB\t\n" +
	"\a_budget\"\x93\x01\n" +
	"\x11GetStatusResponse\x126\n" +
	"\tlightning\x18\x01 \x01(\v2\x13.autoswaprpc.StatusH\x00R\tlightning\x88\x01\x01\x12.\n" +
	"\x05chain\x18\x02 \x01(\v2\x13.autoswaprpc.StatusH\x01R\x05chain\x88\x01\x01B\f\n" +
	"\n" +
	"_lightningB\b\n" +
	"\x06_chain\"\x12\n" +
	"\x10GetConfigRequest\"\xc4\x01\n" +
	"\x1cUpdateLightningConfigRequest\x129\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.autoswaprpc.LightningConfigH\x00R\x06config\x88\x01\x01\x129\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskR\tfieldMask\x12\x19\n" +
	"\x05reset\x18\x03 \x01(\bH\x01R\x05reset\x88\x01\x01B\t\n" +
	"\a_configB\b\n" +
	"\x06_reset\"\xc0\x01\n" +
	"\x18UpdateChainConfigRequest\x120\n" +
	"\x06config\x18\x01 \x01(\v2\x18.autoswaprpc.ChainConfigR\x06config\x12>\n" +
	"\n" +
	"field_mask\x18\x02 \x01(\v2\x1a.google.protobuf.FieldMaskH\x00R\tfieldMask\x88\x01\x01\x12\x19\n" +
	"\x05reset\x18\x03 \x01(\bH\x01R\x05reset\x88\x01\x01B\r\n" +
	"\v_field_maskB\b\n" +
	"\x06_reset\"t\n" +
	"\x06Config\x12.\n" +
	"\x05chain\x18\x01 \x03(\v2\x18.autoswaprpc.ChainConfigR\x05chain\x12:\n" +
	"\tlightning\x18\x02 \x03(\v2\x1c.autoswaprpc.LightningConfigR\tlightning\"\xdf\x02\n" +
	"\vChainConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x1f\n" +
	"\vfrom_wallet\x18\x02 \x01(\tR\n" +
	"fromWallet\x12\x1b\n" +
	"\tto_wallet\x18\x03 \x01(\tR\btoWallet\x12\x1d\n" +
	"\n" +
	"to_address\x18\x04 \x01(\tR\ttoAddress\x12\x1f\n" +
	"\vmax_balance\x18\x05 \x01(\x04R\n" +
	"maxBalance\x12'\n" +
	"\x0freserve_balance\x18\n" +
	" \x01(\x04R\x0ereserveBalance\x12&\n" +
	"\x0fmax_fee_percent\x18\x06 \x01(\x02R\rmaxFeePercent\x12\x16\n" +
	"\x06budget\x18\a \x01(\x04R\x06budget\x12'\n" +
	"\x0fbudget_interval\x18\b \x01(\x04R\x0ebudgetInterval\x12\x1b\n" +
	"\x06tenant\x18\t \x01(\tH\x00R\x06tenant\x88\x01\x01B\t\n" +
	"\a_tenant\"\xdf\x05\n" +
	"\x0fLightningConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x122\n" +
	"\x15channel_poll_interval\x18\x02 \x01(\x04R\x13channelPollInterval\x12%\n" +
	"\x0estatic_address\x18\x03 \x01(\tR\rstaticAddress\x12)\n" +
	"\x10outbound_balance\x18\x04 \x01(\x04R\x0foutboundBalance\x12'\n" +
	"\x0finbound_balance\x18\x05 \x01(\x04R\x0einboundBalance\x128\n" +
	"\x18outbound_balance_percent\x18\x06 \x01(\x02R\x16outboundBalancePercent\x126\n" +
	"\x17inbound_balance_percent\x18\a \x01(\x02R\x15inboundBalancePercent\x12&\n" +
	"\x0fmax_fee_percent\x18\b \x01(\x02R\rmaxFeePercent\x12(\n" +
	"\x10accept_zero_conf\x18\t \x01(\bR\x0eacceptZeroConf\x12'\n" +
	"\x0ffailure_backoff\x18\n" +
	" \x01(\x04R\x0efailureBackoff\x12\x16\n" +
	"\x06budget\x18\v \x01(\x04R\x06budget\x12'\n" +
	"\x0fbudget_interval\x18\f \x01(\x04R\x0ebudgetInterval\x12/\n" +
	"\bcurrency\x18\r \x01(\x0e2\x13.lightzrpc.CurrencyR\bcurrency\x12\x1b\n" +
	"\tswap_type\x18\x0e \x01(\tR\bswapType\x12\x1f\n" +
	"\vper_channel\x18\x0f \x01(\bR\n" +
	"perChannel\x12\x16\n" +
	"\x06wallet\x18\x10 \x01(\tR\x06wallet\x12&\n" +
	"\x0fmax_swap_amount\x18\x11 \x01(\x04R\rmaxSwapAmount\x12\x1b\n" +
	"\x06tenant\x18\x12 \x01(\tH\x00R\x06tenant\x88\x01\x01B\t\n" +
	"\a_tenant2\xd8\x04\n" +
	"\bAutoSwap\x12e\n" +
	"\x12GetRecommendations\x12&.autoswaprpc.GetRecommendationsRequest\x1a'.autoswaprpc.GetRecommendationsResponse\x12q\n" +
	"\x16ExecuteRecommendations\x12*.autoswaprpc.ExecuteRecommendationsRequest\x1a+.autoswaprpc.ExecuteRecommendationsResponse\x12J\n" +
	"\tGetStatus\x12\x1d.autoswaprpc.GetStatusRequest\x1a\x1e.autoswaprpc.GetStatusResponse\x12W\n" +
	"\x15UpdateLightningConfig\x12).autoswaprpc.UpdateLightningConfigRequest\x1a\x13.autoswaprpc.Config\x12O\n" +
	"\x11UpdateChainConfig\x12%.autoswaprpc.UpdateChainConfigRequest\x1a\x13.autoswaprpc.Config\x12?\n" +
	"\tGetConfig\x12\x1d.autoswaprpc.GetConfigRequest\x1a\x13.autoswaprpc.Config\x12;\n" +
	"\fReloadConfig\x12\x16.google.protobuf.Empty\x1a\x13.autoswaprpc.ConfigB>Z<github.com/lightzapp/lightz-client/pkg/lightzrpc/autoswaprpcb\x06proto3"

var (
	file_autoswaprpc_autoswaprpc_proto_rawDescOnce sync.Once
	file_autoswaprpc_autoswaprpc_proto_rawDescData []byte
)

func file_autoswaprpc_autoswaprpc_proto_rawDescGZIP() []byte {
	file_autoswaprpc_autoswaprpc_proto_rawDescOnce.Do(func() {
		file_autoswaprpc_autoswaprpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_autoswaprpc_autoswaprpc_proto_rawDesc), len(file_autoswaprpc_autoswaprpc_proto_rawDesc)))
	})
	return file_autoswaprpc_autoswaprpc_proto_rawDescData
}

var file_autoswaprpc_autoswaprpc_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_autoswaprpc_autoswaprpc_proto_goTypes = []any{
	(*GetRecommendationsRequest)(nil),      // 0: autoswaprpc.GetRecommendationsRequest
	(*LightningSwap)(nil),                  // 1: autoswaprpc.LightningSwap
	(*LightningThresholds)(nil),            // 2: autoswaprpc.LightningThresholds
	(*LightningRecommendation)(nil),        // 3: autoswaprpc.LightningRecommendation
	(*ChainSwap)(nil),                      // 4: autoswaprpc.ChainSwap
	(*ChainRecommendation)(nil),            // 5: autoswaprpc.ChainRecommendation
	(*Budget)(nil),                         // 6: autoswaprpc.Budget
	(*GetRecommendationsResponse)(nil),     // 7: autoswaprpc.GetRecommendationsResponse
	(*ExecuteRecommendationsRequest)(nil),  // 8: autoswaprpc.ExecuteRecommendationsRequest
	(*ExecuteRecommendationsResponse)(nil), // 9: autoswaprpc.ExecuteRecommendationsResponse
	(*GetStatusRequest)(nil),               // 10: autoswaprpc.GetStatusRequest
	(*Status)(nil),                         // 11: autoswaprpc.Status
	(*GetStatusResponse)(nil),              // 12: autoswaprpc.GetStatusResponse
	(*GetConfigRequest)(nil),               // 13: autoswaprpc.GetConfigRequest
	(*UpdateLightningConfigRequest)(nil),   // 14: autoswaprpc.UpdateLightningConfigRequest
	(*UpdateChainConfigRequest)(nil),       // 15: autoswaprpc.UpdateChainConfigRequest
	(*Config)(nil),                         // 16: autoswaprpc.Config
	(*ChainConfig)(nil),                    // 17: autoswaprpc.ChainConfig
	(*LightningConfig)(nil),                // 18: autoswaprpc.LightningConfig
	(lightzrpc.SwapType)(0),                // 19: lightzrpc.SwapType
	(*lightzrpc.LightningChannel)(nil),     // 20: lightzrpc.LightningChannel
	(*lightzrpc.Balance)(nil),              // 21: lightzrpc.Balance
	(*lightzrpc.SwapStats)(nil),            // 22: lightzrpc.SwapStats
	(*field_mask.FieldMask)(nil),           // 23: google.protobuf.FieldMask
	(lightzrpc.Currency)(0),                // 24: lightzrpc.Currency
	(*empty.Empty)(nil),                    // 25: google.protobuf.Empty
}
var file_autoswaprpc_autoswaprpc_proto_depIdxs = []int32{
	19, // 0: autoswaprpc.LightningSwap.type:type_name -> lightzrpc.SwapType
	1,  // 1: autoswaprpc.LightningRecommendation.swap:type_name -> autoswaprpc.LightningSwap
	20, // 2: autoswaprpc.LightningRecommendation.channel:type_name -> lightzrpc.LightningChannel
	2,  // 3: autoswaprpc.LightningRecommendation.thresholds:type_name -> autoswaprpc.LightningThresholds
	4,  // 4: autoswaprpc.ChainRecommendation.swap:type_name -> autoswaprpc.ChainSwap
	21, // 5: autoswaprpc.ChainRecommendation.wallet_balance:type_name -> lightzrpc.Balance
	22, // 6: autoswaprpc.Budget.stats:type_name -> lightzrpc.SwapStats
	3,  // 7: autoswaprpc.GetRecommendationsResponse.lightning:type_name -> autoswaprpc.LightningRecommendation
	5,  // 8: autoswaprpc.GetRecommendationsResponse.chain:type_name -> autoswaprpc.ChainRecommendation
	3,  // 9: autoswaprpc.ExecuteRecommendationsRequest.lightning:type_name -> autoswaprpc.LightningRecommendation
	5,  // 10: autoswaprpc.ExecuteRecommendationsRequest.chain:type_name -> autoswaprpc.ChainRecommendation
	6,  // 11: autoswaprpc.Status.budget:type_name -> autoswaprpc.Budget
	11, // 12: autoswaprpc.GetStatusResponse.lightning:type_name -> autoswaprpc.Status
	11, // 13: autoswaprpc.GetStatusResponse.chain:type_name -> autoswaprpc.Status
	18, // 14: autoswaprpc.UpdateLightningConfigRequest.config:type_name -> autoswaprpc.LightningConfig
	23, // 15: autoswaprpc.UpdateLightningConfigRequest.field_mask:type_name -> google.protobuf.FieldMask
	17, // 16: autoswaprpc.UpdateChainConfigRequest.config:type_name -> autoswaprpc.ChainConfig
	23, // 17: autoswaprpc.UpdateChainConfigRequest.field_mask:type_name -> google.protobuf.FieldMask
	17, // 18: autoswaprpc.Config.chain:type_name -> autoswaprpc.ChainConfig
	18, // 19: autoswaprpc.Config.lightning:type_name -> autoswaprpc.LightningConfig
	24, // 20: autoswaprpc.LightningConfig.currency:type_name -> lightzrpc.Currency
	0,  // 21: autoswaprpc.AutoSwap.GetRecommendations:input_type -> autoswaprpc.GetRecommendationsRequest
	8,  // 22: autoswaprpc.AutoSwap.ExecuteRecommendations:input_type -> autoswaprpc.ExecuteRecommendationsRequest
	10, // 23: autoswaprpc.AutoSwap.GetStatus:input_type -> autoswaprpc.GetStatusRequest
	14, // 24: autoswaprpc.AutoSwap.UpdateLightningConfig:input_type -> autoswaprpc.UpdateLightningConfigRequest
	15, // 25: autoswaprpc.AutoSwap.UpdateChainConfig:input_type -> autoswaprpc.UpdateChainConfigRequest
	13, // 26: autoswaprpc.AutoSwap.GetConfig:input_type -> autoswaprpc.GetConfigRequest
	25, // 27: autoswaprpc.AutoSwap.ReloadConfig:input_type -> google.protobuf.Empty
	7,  // 28: autoswaprpc.AutoSwap.GetRecommendations:output_type -> autoswaprpc.GetRecommendationsResponse
	9,  // 29: autoswaprpc.AutoSwap.ExecuteRecommendations:output_type -> autoswaprpc.ExecuteRecommendationsResponse
	12, // 30: autoswaprpc.AutoSwap.GetStatus:output_type -> autoswaprpc.GetStatusResponse
	16, // 31: autoswaprpc.AutoSwap.UpdateLightningConfig:output_type -> autoswaprpc.Config
	16, // 32: autoswaprpc.AutoSwap.UpdateChainConfig:output_type -> autoswaprpc.Config
	16, // 33: autoswaprpc.AutoSwap.GetConfig:output_type -> autoswaprpc.Config
	16, // 34: autoswaprpc.AutoSwap.ReloadConfig:output_type -> autoswaprpc.Config
	28, // [28:35] is the sub-list for method output_type
	21, // [21:28] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_autoswaprpc_autoswaprpc_proto_init() }
func file_autoswaprpc_autoswaprpc_proto_init() {
	if File_autoswaprpc_autoswaprpc_proto != nil {
		return
	}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[2].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[3].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[5].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[6].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[8].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[11].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[12].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[14].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[15].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[17].OneofWrappers = []any{}
	file_autoswaprpc_autoswaprpc_proto_msgTypes[18].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_autoswaprpc_autoswaprpc_proto_rawDesc), len(file_autoswaprpc_autoswaprpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_autoswaprpc_autoswaprpc_proto_goTypes,
		DependencyIndexes: file_autoswaprpc_autoswaprpc_proto_depIdxs,
		MessageInfos:      file_autoswaprpc_autoswaprpc_proto_msgTypes,
	}.Build()
	File_autoswaprpc_autoswaprpc_proto = out.File
	file_autoswaprpc_autoswaprpc_proto_goTypes = nil
	file_autoswaprpc_autoswaprpc_proto_depIdxs = nil
}
